import os
import subprocess
from pathlib import Path
import secrets

from code_index.path_security import validate_root_dir

CONFIG_FILENAME = ".codeindex.yml"

DEFAULT_CONFIG = """\
# codeindex configuration
# Generated by code_index — edit freely

codebases:
  # - name: my_project
  #   root: ./src

extensions:
  - .py
  - .js
  - .jsx
  - .ts
  - .tsx
  - .md
  - .txt
  - .json
  - .sql

exclude:
  - node_modules
  - .venv
  - __pycache__
  - .git
"""


def find_git_root(path=None):
    start = Path(path or os.getcwd()).resolve()
    current = start
    while current != current.parent:
        if (current / ".git").exists():
            return str(current)
        current = current.parent
    return None


def _detect_codebases_from_git_root(git_root):
    codebases = []
    root_name = os.path.basename(git_root)
    codebases.append({"name": root_name, "root": git_root})
    return codebases


def _generate_encryption_key():
    return secrets.token_urlsafe(32)


def _interactive_setup(start_dir=None):
    start_dir = start_dir or os.getcwd()
    git_root = find_git_root(start_dir)

    print()
    print("=" * 50)
    print("  codeindex — first-time setup")
    print("=" * 50)
    print()

    if git_root:
        print(f"  Detected git repo: {git_root}")
        print()

    print("  Options:")
    print("  1) Index git repo root (auto-detected)" if git_root else "  1) [skip — no git repo found]")
    print("  2) Index current directory")
    print("  3) Enter paths manually")
    print()

    while True:
        choice = input("  Choose [1/2/3]: ").strip()
        codebases = []

        if choice == "1" and git_root:
            codebases = _detect_codebases_from_git_root(git_root)
            break
        elif choice == "2":
            root = os.getcwd()
            name = os.path.basename(root)
            codebases.append({"name": name, "root": root})
            break
        elif choice == "3":
            print("  Enter directory paths (one per line, blank line to finish):")
            while True:
                raw = input("    ").strip()
                if not raw:
                    break
                p = os.path.abspath(os.path.expanduser(raw))
                if not os.path.isdir(p):
                    print(f"    [skipped — not a directory: {p}]")
                    continue
                try:
                    p = validate_root_dir(p)
                except ValueError as e:
                    print(f"    [skipped — {e}]")
                    continue
                name = os.path.basename(p)
                codebases.append({"name": name, "root": p})
            if codebases:
                break
            print("  No valid directories entered. Try again.")
        else:
            print("  Invalid choice. Try again.")

    return codebases


def generate_config(codebases, extensions=None, exclude=None):
    extensions = extensions or [
        ".py", ".js", ".jsx", ".ts", ".tsx", ".md", ".txt", ".json", ".sql",
    ]
    exclude = exclude or ["node_modules", ".venv", "__pycache__", ".git"]

    lines = ["# codeindex configuration", "# Generated by code_index", ""]
    lines.append("codebases:")
    for cb in codebases:
        lines.append(f"  - name: {cb['name']}")
        lines.append(f"    root: {cb['root']}")
    lines.append("")
    lines.append("extensions:")
    for ext in extensions:
        lines.append(f"  - {ext}")
    lines.append("")
    lines.append("exclude:")
    for exc in exclude:
        lines.append(f"  - {exc}")
    lines.append("")
    return "\n".join(lines)


def save_config(config_text, path=None):
    config_path = path or os.path.join(os.getcwd(), CONFIG_FILENAME)
    with open(config_path, "w") as f:
        f.write(config_text)
    return config_path


def run_setup(start_dir=None, config_path=None):
    config_path = config_path or os.path.join(start_dir or os.getcwd(), CONFIG_FILENAME)
    codebases = _interactive_setup(start_dir)
    config_text = generate_config(codebases)
    saved_path = save_config(config_text, config_path)
    enc_key = _generate_encryption_key()

    env_path = os.path.join(os.path.dirname(saved_path), ".env")
    env_lines = []
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            env_lines = [l for l in f.readlines() if not l.startswith("CODE_INDEX_DB_ENCRYPTION_KEY=")]
    env_lines.append(f"CODE_INDEX_DB_ENCRYPTION_KEY={enc_key}\n")
    with open(env_path, "w") as f:
        f.writelines(env_lines)

    print()
    print(f"  Config saved to {saved_path}")
    print(f"  Codebases: {', '.join(cb['name'] for cb in codebases)}")
    print(f"  Encryption key generated and saved to {env_path}")
    print()
    return codebases


def quick_setup(project_path, config_save_dir=None):
    project_path = os.path.abspath(project_path)
    name = os.path.basename(project_path)
    codebases = [{"name": name, "root": project_path}]
    config_text = generate_config(codebases)
    saved_path = save_config(config_text, config_save_dir)
    enc_key = _generate_encryption_key()

    env_path = os.path.join(os.path.dirname(saved_path), ".env")
    env_lines = []
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            env_lines = [l for l in f.readlines() if not l.startswith("CODE_INDEX_DB_ENCRYPTION_KEY=")]
    env_lines.append(f"CODE_INDEX_DB_ENCRYPTION_KEY={enc_key}\n")
    with open(env_path, "w") as f:
        f.writelines(env_lines)

    print()
    print(f"  Config saved to {saved_path}")
    print(f"  Codebase: {name} -> {project_path}")
    print(f"  Encryption key generated and saved to {env_path}")
    print()
    return codebases
